#!/usr/bin/env python3
"""
Download and self-host the two webfonts.

Google Fonts' CSS2 API serves different formats depending on the requesting
User-Agent: an old/unknown UA gets TTF, a modern Chrome UA gets woff2. We ask
as Chrome so we get woff2, then rewrite the @font-face CSS to point at local
files. Self-hosting means no third-party request on the critical path and no
dependency on fonts.googleapis.com being reachable.

    python tests/fetch_fonts.py
"""

import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).parent.parent
FONT_DIR = ROOT / "docs" / "assets" / "fonts"
CSS_OUT = ROOT / "docs" / "assets" / "css" / "fonts.css"

CHROME_UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
)

FAMILIES = [
    # (label, css2 query, local filename stem)
    ("Fraunces",
     "family=Fraunces:opsz,wght@9..144,300..900",
     "fraunces"),
    ("Archivo",
     "family=Archivo:wght@100..900",
     "archivo"),
]

# Only the subsets we actually need. Google emits one @font-face per subset.
WANTED_SUBSETS = {"latin", "latin-ext"}


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": CHROME_UA})
    with urllib.request.urlopen(req, timeout=45) as resp:
        return resp.read()


def main():
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    blocks_out = []

    for label, query, stem in FAMILIES:
        url = f"https://fonts.googleapis.com/css2?{query}&display=swap"
        css = fetch(url).decode("utf-8")

        if "woff2" not in css:
            sys.exit(
                f"  {label}: Google returned no woff2 (got TTF?). "
                f"The User-Agent spoof may have stopped working."
            )

        # Google's CSS is a sequence of "/* subset */ @font-face {...}" blocks.
        parts = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
        # parts = ['', subset, block, subset, block, ...]
        kept = 0
        for i in range(1, len(parts) - 1, 2):
            subset = parts[i].strip()
            block = parts[i + 1]
            if subset not in WANTED_SUBSETS:
                continue

            m = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not m:
                continue
            remote = m.group(1)

            filename = f"{stem}-{subset}.woff2"
            data = fetch(remote)
            (FONT_DIR / filename).write_bytes(data)

            block = block.replace(remote, f"../fonts/{filename}")
            block = block.strip()
            blocks_out.append(f"/* {label} — {subset} */\n{block}")
            kept += 1
            print(f"  {label:10} {subset:10} {len(data) / 1024:6.1f} KB  -> {filename}")

        if kept == 0:
            sys.exit(f"  {label}: no matching subsets found.")

    header = (
        "/* Generated by tests/fetch_fonts.py — self-hosted webfonts.\n"
        "   Fraunces and Archivo are licensed under the SIL Open Font License 1.1. */\n\n"
    )
    CSS_OUT.write_text(header + "\n\n".join(blocks_out) + "\n", encoding="utf-8")

    total = sum(f.stat().st_size for f in FONT_DIR.glob("*.woff2"))
    print(f"\n  {len(list(FONT_DIR.glob('*.woff2')))} files, "
          f"{total / 1024:.0f} KB total -> docs/assets/fonts/")
    print(f"  Wrote {CSS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
